// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	GetNotificationsByUser(ctx context.Context, userID pgtype.UUID) ([]Notification, error)
}

var _ Querier = (*Queries)(nil)
