// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID        pgtype.UUID      `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	LastLogin pgtype.Timestamp `json:"last_login"`
}

type LoginAttempt struct {
	ID          pgtype.UUID      `json:"id"`
	Username    string           `json:"username"`
	Success     bool             `json:"success"`
	AttemptTime pgtype.Timestamp `json:"attempt_time"`
}

type Session struct {
	ID               pgtype.UUID      `json:"id"`
	UserID           pgtype.UUID      `json:"user_id"`
	SessionToken     string           `json:"session_token"`
	SessionExpiresAt pgtype.Timestamp `json:"session_expires_at"`
}
