// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAllSessionsForUser(ctx context.Context, userID pgtype.UUID) error
	DeleteOldLoginAttempts(ctx context.Context) error
	DeleteSessionByToken(ctx context.Context, sessionToken string) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetFailedLoginAttemptsByUsername(ctx context.Context, arg GetFailedLoginAttemptsByUsernameParams) ([]LoginAttempt, error)
	GetLoginAttemptsByUsername(ctx context.Context, arg GetLoginAttemptsByUsernameParams) ([]LoginAttempt, error)
	GetSessionByToken(ctx context.Context, sessionToken string) (GetSessionByTokenRow, error)
	GetSessionByUserId(ctx context.Context, userID pgtype.UUID) ([]GetSessionByUserIdRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (Auth, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	LogFailedLogin(ctx context.Context, username string) error
	LogSuccessfulLogin(ctx context.Context, username string) error
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateSessionExpiry(ctx context.Context, arg UpdateSessionExpiryParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
