// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID         pgtype.UUID      `json:"id"`
	PostID     pgtype.UUID      `json:"post_id"`
	UserID     pgtype.UUID      `json:"user_id"`
	Content    string           `json:"content"`
	LikesCount pgtype.Int4      `json:"likes_count"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Label struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type LabelsPost struct {
	LabelID pgtype.UUID `json:"label_id"`
	PostID  pgtype.UUID `json:"post_id"`
}

type Like struct {
	ID        pgtype.UUID      `json:"id"`
	PostID    pgtype.UUID      `json:"post_id"`
	CommentID pgtype.UUID      `json:"comment_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Post struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	LikesCount  pgtype.Int4      `json:"likes_count"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}
