// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddLabelToPost(ctx context.Context, arg AddLabelToPostParams) error
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateLikeForComment(ctx context.Context, arg CreateLikeForCommentParams) error
	CreateLikeForPost(ctx context.Context, arg CreateLikeForPostParams) error
	CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error)
	DeleteLikeForComment(ctx context.Context, arg DeleteLikeForCommentParams) error
	DeleteLikeForPost(ctx context.Context, arg DeleteLikeForPostParams) error
	DeletePost(ctx context.Context, id pgtype.UUID) error
	GetAllLabels(ctx context.Context) ([]Label, error)
	GetCommentsByPostID(ctx context.Context, postID pgtype.UUID) ([]Comment, error)
	GetLabelsForPost(ctx context.Context, postID pgtype.UUID) ([]Label, error)
	GetLikesCountForComment(ctx context.Context, commentID pgtype.UUID) (pgtype.Int4, error)
	GetLikesCountForPost(ctx context.Context, postID pgtype.UUID) (pgtype.Int4, error)
	GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error)
	GetPostsByLabel(ctx context.Context, labelID pgtype.UUID) ([]GetPostsByLabelRow, error)
	GetPostsWithCommentsAndLikes(ctx context.Context) ([]GetPostsWithCommentsAndLikesRow, error)
	RemoveLabelFromPost(ctx context.Context, arg RemoveLabelFromPostParams) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) error
}

var _ Querier = (*Queries)(nil)
